[package]
name = "rubiks-cube-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
num-traits = "0.2"
num-derive = "0.3"
yansi = "0.5.1"
